# Common defaults used across scenario tests.
appName: "test"

backup:
  trigger:
    schedule: "0 1 * * *"
  pruneIntervalDays: 7
  cache:
    capacity: 2Gi
  pvc:
    storageClass: longhorn
    volumeSnapshotClass: longhorn-snapshot

restic:
  runAsUser: 65534
  runAsGroup: 65534
  fsGroup: 65534

s3:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  secretKey: backblaze-volsync

restore:
  cache:
    capacity: "1Gi"
  enabled: true
  enableFileDeletion: true
  pvc:
    size: 10Gi
    name: foo
  restoreAsOf: "2024-01-15T10:30:00Z"
