# Common defaults used across scenario tests.
appName: "test"

backup:
  trigger:
    schedule: "0 1 * * *"
    manual: backup-now
  pruneIntervalDays: 7
  cacheCapacity: 2Gi
  pvcName: test-data
  storageClass: longhorn
  volumeSnapshotClass: longhorn-snapshot

restic:
  runAsUser: 65534
  runAsGroup: 65534
  fsGroup: 65534

s3:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  secretKey: backblaze-volsync

restore:
  enabled: true
  cacheCapacity: "1Gi"
  enableFileDeletion: true
  pvcSize: 10Gi
  pvcName: foo
  storageClass: ceph-block
  restoreAsOf: "2024-01-15T10:30:00Z"
