{{ if .Values.restore.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.restore.pvcName | default .Values.backup.pvcName }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.argoSyncWave }}
spec:
  accessModes: {{ .Values.restore.accessModes }}
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: {{ include "chart.repository" . }}
  resources:
    requests:
      storage: {{ required ".Values.restore.pvcSize is required" .Values.restore.pvcSize }}
  storageClassName: {{ .Values.restore.storageClass | default .Values.backup.storageClass }}
{{ end }}
